name: Front Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
  AWS_S3_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
  AWS_CLOUDFRONT_ID: E28E59CC0SK52X
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  NEXT_PUBLIC_NOTION_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_NOTION_DATABASE_ID }}
  NEXT_PUBLIC_NOTION_KEY: ${{ secrets.NEXT_PUBLIC_NOTION_KEY }}

jobs:
  build:
    name: build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout Github Action
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: generate env file
        run: |
          echo "NEXT_PUBLIC_NOTION_DATABASE_ID=${{ env.NEXT_PUBLIC_NOTION_DATABASE_ID }}" >> .env
          echo "NEXT_PUBLIC_NOTION_API_KEY=${{ env.NEXT_PUBLIC_NOTION_API_KEY }}" >> .env

      - name: build
        run: pnpm build

      - name: post build
        run: pnpm postbuild

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_S3_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ env.AWS_S3_BUCKET_NAME}}
        run: |
          aws s3 sync \
            ./out s3://$BUCKET_NAME --delete

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"
